/**
 * Bootstraps the local Lightning regtest network for TrailPay:
 *   1. extracts TLS certs + admin macaroons from the running LND containers
 *   2. mines regtest coins to the payer node
 *   3. opens a payer -> payee channel with spendable liquidity
 *   4. writes .env.local so the app talks to real nodes (LIGHTNING_BACKEND=lnd)
 *
 * Prereq: `npm run ln:up` (docker compose up). Then: `npm run ln:setup`.
 */
import { execSync } from "child_process";
import { readFileSync, writeFileSync, mkdtempSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import {
  authenticatedLndGrpc,
  getWalletInfo,
  getChainBalance,
  createChainAddress,
  addPeer,
  openChannel,
  getChannels,
} from "lightning";

const BITCOIND_RPC = "http://127.0.0.1:18443/";
const BITCOIND_AUTH = "Basic " + Buffer.from("trailpay:trailpay").toString("base64");
const CHANNEL_SATS = 5_000_000;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function dockerCpBase64(container: string, path: string): string {
  const tmp = mkdtempSync(join(tmpdir(), "trailpay-"));
  const dest = join(tmp, "f");
  execSync(`docker cp ${container}:${path} "${dest}"`, { stdio: "pipe" });
  return readFileSync(dest).toString("base64");
}

async function bitcoind(method: string, params: unknown[] = []) {
  const res = await fetch(BITCOIND_RPC, {
    method: "POST",
    headers: { "content-type": "text/plain", authorization: BITCOIND_AUTH },
    body: JSON.stringify({ jsonrpc: "1.0", id: "trailpay", method, params }),
  });
  const json = (await res.json()) as { result?: unknown; error?: { message: string } };
  if (json.error) throw new Error(`${method}: ${json.error.message}`);
  return json.result;
}

async function waitFor<T>(label: string, fn: () => Promise<T | null>, tries = 60): Promise<T> {
  for (let i = 0; i < tries; i++) {
    try {
      const v = await fn();
      if (v) return v;
    } catch {
      /* retry */
    }
    await sleep(1000);
  }
  throw new Error(`Timed out waiting for: ${label}`);
}

async function main() {
  console.log("→ Reading credentials from containers…");
  const payeeCert = dockerCpBase64("trailpay-lnd-payee", "/home/lnd/.lnd/tls.cert");
  const payerCert = dockerCpBase64("trailpay-lnd-payer", "/home/lnd/.lnd/tls.cert");
  const macPath = "/home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon";
  const payeeMac = dockerCpBase64("trailpay-lnd-payee", macPath);
  const payerMac = dockerCpBase64("trailpay-lnd-payer", macPath);

  const { lnd: payee } = authenticatedLndGrpc({
    socket: "127.0.0.1:10009",
    cert: payeeCert,
    macaroon: payeeMac,
  });
  const { lnd: payer } = authenticatedLndGrpc({
    socket: "127.0.0.1:10010",
    cert: payerCert,
    macaroon: payerMac,
  });

  console.log("→ Waiting for LND nodes to be ready…");
  const payeeInfo = await waitFor("payee ready", () => getWalletInfo({ lnd: payee }));
  const payerInfo = await waitFor("payer ready", () => getWalletInfo({ lnd: payer }));
  console.log(`  payee=${payeeInfo.public_key.slice(0, 12)}… payer=${payerInfo.public_key.slice(0, 12)}…`);

  console.log("→ Funding payer with regtest coins…");
  const { address } = await createChainAddress({ lnd: payer, format: "p2wpkh" });
  await bitcoind("generatetoaddress", [110, address]);
  await waitFor(
    "payer chain balance",
    async () => ((await getChainBalance({ lnd: payer })).chain_balance > 0 ? true : null),
  );

  console.log("→ Connecting peer + opening channel…");
  try {
    await addPeer({ lnd: payer, public_key: payeeInfo.public_key, socket: "lnd_payee:9735" });
  } catch {
    /* may already be connected */
  }
  await openChannel({
    lnd: payer,
    partner_public_key: payeeInfo.public_key,
    local_tokens: CHANNEL_SATS,
  });
  await bitcoind("generatetoaddress", [6, address]);

  console.log("→ Waiting for channel to activate…");
  await waitFor("active channel", async () => {
    const { channels } = await getChannels({ lnd: payer });
    return channels.some((c) => c.is_active) ? true : null;
  });

  const env = [
    "# Generated by scripts/setup-lnd.ts — real Lightning regtest backend",
    "LIGHTNING_BACKEND=lnd",
    "DEMO_MODE=true",
    "LND_PAYEE_SOCKET=127.0.0.1:10009",
    `LND_PAYEE_CERT=${payeeCert}`,
    `LND_PAYEE_MACAROON=${payeeMac}`,
    "LND_PAYER_SOCKET=127.0.0.1:10010",
    `LND_PAYER_CERT=${payerCert}`,
    `LND_PAYER_MACAROON=${payerMac}`,
    "",
  ].join("\n");
  writeFileSync(join(process.cwd(), ".env.local"), env);

  console.log("\n✅ Lightning regtest ready. Wrote .env.local (LIGHTNING_BACKEND=lnd).");
  console.log("   Restart the dev server to use real nodes:  npm run dev\n");
}

main().catch((e) => {
  console.error("\n❌ setup-lnd failed:", e.message);
  process.exit(1);
});
